# # require 'pry'
#
# articles = "1/25/16 15:27,East Ramapo| state hit with yeshiva lawsuit,http://www.lohud.com/story/news/education/2015/11/20/east-ramapo-yeshivas-suit/75893324/,11/20/15,Adrienne Sanders,Lawsuit filed,Two months after the publication of my original story about the lack of secular studies in Hasidic yeshivas in Rockland County| a group of former yeshiva students and parents of current students filed a class-action civil rights lawsuit that accuses education officials| school administrators and the East Ramapo district superintendent of failing to provide boys with a sound| basic education.,The lawyer who filed the suit credited our coverage on the issue with emboldening Hasidic families to come forward as plaintiffs. (Still| they filed without identifying themselves for fear of community retribution.),LineEnd
# 1/25/16 17:25,Metro-North accidents cost $38M and climbing,http://www.usatoday.com/story/news/investigations/2015/10/21/metro-north-lawsuits/74229694/,10/21/15,Thomas C. Zambito,Staff interview on other media,Appeared on NY1's 'In Transit' on 1/8/16 to discuss our story on the $38 million in legal costs Metro-North has incurred to settle lawsuits filed in the wake of several derailments.,No Data,LineEnd
# 1/25/16 17:29,Metro-North workers cash in to fix rails,http://www.lohud.com/story/news/investigations/2016/01/21/metro-north-ot/78854948/,1/22/16,Thomas C. Zambito,Law change| policy change,After the story was published| the Federal Railroad Administration announced that it was considering a rule change that would limit the amount of hours track workers are allowed to put in during a day.,After the story was published| the Federal Railroad Administration said it was considering a change to work rules that have allowed track workers to work around the clock.,LineEnd
# 1/25/16 17:35,Facing a legend: St. Thomas Aquinas Opens the Season Against St. John's,http://www.usatoday.com/story/sports/basketball/2015/11/04/facing-legend-st-thomas-aquinas-opens-season-against-st-johns/74338722/,11/3/15,Thomas C. Zambito,Social share by key figure or organization,Retweet by college basketball analyst Jay Bilas| who has 1M followers,No Data,LineEnd
# 1/26/16 10:12,Pain-pill abuse kills hundreds in our suburbs & Painkillers to Heroin: A Generation Lost,Painkillers to Heroin: A Generation Lost - http://www.lohud.com/longform/news/investigations/2015/12/03/heroin-new-york/75226754/ Pain-pill abuse kills hundreds in our suburbs - http://www.lohud.com/story/news/investigations/2015/10/01/pain-pill-abuse/32287313/,12/3/15,David Robinson,Law change| policy change| Advocacy organization uses our journalism| Staff interview on other media| Social share by key figure or organization| Reporter followed by key figure or organization on social media| Citation (someone mentioned your journalism in an important way)| How much our audience�s awareness or understanding has increased| Reader/viewer contact,'Pill docs I was quoted on WOR 710 news radio in NYC market. I was interviewed on WFAS 1230 in White Plains based on the impact of Painkillers to Heroin: A generation lost.
#
# Health teachers in Yonkers school district have incorporated Painkillers to Heroin: A generation lost into lesson plans.
#
# CMS| the federal agency that oversees Medicare and Medicaid| launched an interactive mapping tool to track opioid pain pill prescribing data by community today (With a focus on helping the public learn more about which doctors are filing Medicare claims for opioids) A CMS official cited my coverage of the issue in an email related to the mapping press release: The tool can be accessed here: http://go.cms.gov/opioidheatmap.
#
# New York Department of Health officials provided data to federal DEA agents and prosecutors in connection to the October 1 arrest of Dr. Alfred Ramirez| according to court records. That information seems to have been shared as part of a policy shift as I was investigating the impact of the DOH's failure to provide narcotics prescribing records previously.
#
# News-Press in Fort Myers and The Des Moines Register and Desert Sun have also linked my coverage for pill docs I and II| and Painkillers to Heroin: A generation lost.
#
# Lohud community conversation taking place based on the coverage.
#
#
#
# ',No Data,LineEnd
# 1/27/16 16:19,Lohud reporter to discuss yeshivas on PBS,http://www.lohud.com/story/news/2016/01/26/adrienne-sanders-appear-pbs/79346452/,1/30/16,Adrienne Sanders,Staff interview on other media,I am appearing on PBS' Religion & Ethics NewsWeekly to discuss the topic of secular education in Hasidic yeshivas. Three sources that appeared in my story are also interviewed on the show. All episodes are available for download at www.pbs.org/wnet/religionandethics.,Yoel Falkowitz| a yeshiva parent interviewed in the PBS show first came forward publicly in my story.,LineEnd
# 1/27/16 16:49,Zebrowski bill to improve non-public school education,http://www.lohud.com/story/news/education/2015/11/24/zebrowski-bill-improve-non-public-school-education/76322088/,11/24/15,Adrienne Sanders,Law change| policy change,In response to a lawsuit seeking to improve secular education in some Hasidic yeshivas| Assemblyman Kenneth Zebrowski| D-New City| crafted a bill that allows the state to enforce the legal standard of �substantial equivalence.� The lawyer who filed that suit credited our coverage with emboldening plaintiffs to come forward with the complaint.,He has since enlisted Sen. Carlucci's support in the senate.,LineEnd
# 1/29/16 15:19,Some E. Ramapo yeshivas fail to prepare pupils in secular studies,http://www.lohud.com/story/news/investigations/2015/09/16/east-ramapo-yeshivas/32482729/,9/18/15,Adrienne Sanders,Law change| policy change| Lawsuit filed| Advocacy organization uses our journalism| Social share by key figure or organization| Reporter followed by key figure or organization on social media| How much our audience�s awareness or understanding has increased| Reader/viewer contact| Made inroads in a community not often represented in our journalism,Non-profits including Strong East Ramapo| Yaffed| Advocates for Justice and several others commented on and shared this story via social media. Ken Zebrowski and (other public officials) followed me on Twitter. Zebrowski drafted a bill to ensure that a sound education is taught in all schools after a lawsuit was filed. (See other entries.) This story included Lohud's entry inside a Hasidic home and included video of a Hasidic father| thus beginning our coverage -- from within -- of a fast-growing and politically powerful community.,'For many readers| this was the first time they had heard anything about how Hasidic yeshivas function -- and the first time they began to understand some of the challenges facing the private schools in East Ramapo.
# The ERCSD board president told me privately that he spent hours responding to calls and questions about the content of this story.',LineEnd
# 2/3/16 10:37,Taser gun seized at Sleepy Hollow HS| police not notified,http://www.lohud.com/story/news/crime/2015/11/03/taser-stun-gun-seized-sleepy-hollow-hs-police-not-notified/75099828/,11/3/15,Jorge Fitz-Gibbon,Institutional action (firing reorganization etc.)| criminal charges filed,My Nov. 3| 2015 story regarding a Taser stun gun seized at Sleepy Hollow High School in Tarrytown was the first of three on the incident. I reported that the Taser was seized from a student but not reported to police. The following day police filed charges against the student. In the most recent story on the incident| published Jan. 5| 2016| the school district acknowledged that officials mishandled the situation. More recently the high school principal has retired.,No Data,LineEnd
# 2/3/16 10:44,Orange Co. official listen Rockland and Orange both as primary homes,http://www.lohud.com/story/news/crime/2015/11/03/taser-stun-gun-seized-sleepy-hollow-hs-police-not-notified/75099828/,11/1/15,Jorge Fitz-Gibbon,Institutional action (firing reorganization etc.)| Public official refers to our journalism| Citation (someone mentioned your journalism in an important way),My story on Bob Livsey| the supervisor of the town of Highlands in Orange County| prompted a court order in his re-election bid. My initial story on Nov. 1| 2015 - the first of three on the matter - reported that Livsey held office in Highlands while listing his Rockland County home as his primary address for veterans and STAR exemptions. After reading my story| Holly Farris-Gokey| who was running against Livsey in the supervisor's race| cited the article to seek and obtain a court order freezing the election results until Livsey's residency issue could be rectified. Livsey was allowed to take office after winning the election| but had to withdraw is veteran's and STAR exemptions at the Rockland home.,No Data,LineEnd
# 2/3/16 10:54,Ex-Mount Vernon official's $3.1M deal raises questions,http://www.lohud.com/story/news/investigations/2015/10/15/ex-mt-vernon-commissioner-contract-ernie-davis-terrence-horton/73605710/,10/15/15,Jorge Fitz-Gibbon,Institutional action (firing reorganization etc.)| Public official refers to our journalism,I wrote my first story on Mount Vernon contractor and former city public works CommissionerTerrence Horton on Oct. 15| 2015. The story revealed that he had been awarded a lucrative contract to replace the city's streetlights with LED lights. The story noted that Horton was awarded the contract from a group of bidders| but that he had signed a contract for the equipment months before the city bid the project| and had signed the deal on an overseas trip to Korea with the mayor and other top city officials. The story also revealed that Horton had financial troubles and owed back taxes on three city properties. He sought a $450|000 advance from the city for the lighting contract. After my story published the city council balked at awarding him the contract. It wasn't until Dec. 18 that Horton was able to convince the city to give him a reduced payment of $336|000.,No Data,LineEnd
# 2/3/16 11:01,Party favors: Dual roles| perks for political bosses,http://www.lohud.com/story/news/investigations/2015/06/20/dual-roles-westchester-political-party-leaders/29035407/,6/20/15,Jorge Fitz-Gibbon,Institutional action (firing| reorganization| etc.)| Advocacy organization uses our journalism| Citation (someone mentioned your journalism in an important way),My expose on the perks enjoyed by Westchester County's political party bosses| both of whom are county elections commissioners| prompted a push by the League of Women Voters to ban the dual roles in the state| revived three bills in Albany to make the ban a law| and inspired an online petition to the same end. The story reported that Democratic Chairman Reggie LaFayette has his own campaign committee that uses donations from developers and connected businessmen to pay for meals| travel and a leased SUV. GOP Chairman Doug Colety owns a printing business that prints most of the Republican campaign literature for GOP candidates. The problem is Colety doesn't have a printing press. He says he's a printing 'broker' who gets a cut of the business. I am now in the process of updating this story with a look at the three bills pending in Albany to make the dual roles illegal.,http://www.lohud.com/story/opinion/contributors/2015/07/11/westchester-election-bosses-listen/29951689/,LineEnd
# 2/3/16 11:54,Racist E-Mails From Pelham Manor Police Chief Revealed,http://www.lohud.com/story/news/local/westchester/2015/02/10/alfred-mosiello-pelham-manor-police-chief-racist-emails/23192363/,2/10/15,Jonathan Bandler,Institutional action (firing reorganization etc.),The Pelham Manor Board of Trustees initially suspended Alfred Mosiello over racist emails he had forwarded. But within days of our revealing some of the emails| the board pressured him to retire. The follow up story ran on Feb. 14| 2015: http://www.lohud.com/story/news/local/westchester/2015/02/14/pelham-manor-police-chief-alfred-mosiello-retires-email-scandal/23440483/,No Data,LineEnd
# 2/3/16 16:02,Is Astorino's housing claim true?,http://www.lohud.com/story/money/personal-finance/taxes/david-mckay-wilson/2016/01/07/astorinos-chappaqua-housing-claim-true/78379282/,1/6/16,David McKay Wilson,Government investigation| Advocacy organization uses our journalism| Public official refers to our journalism| Citation (someone mentioned your journalism in an important way)| Increased civic engagement (participation in the democratic process),the federal housing monitor and the US Justice Department cited the article in filings regarding the town of New Castle's opposition to the project,No Data,LineEnd
# 2/3/16 16:06,NCAA scholarships yanked| WCC coach fired in transcript probe,http://www.lohud.com/story/news/local/westchester/2014/10/24/ncaa-basketball-scholarships-yanked-transcript-fraud-wcc-coach-fired/17864275/,10/24/14,Lee Higgins,Government investigation| Institutional action (firing reorganization etc.)| Staff interview on other media| Social share by key figure or organization| Citation (someone mentioned your journalism in an important way)| Award,My reporting on transcript fraud in college basketball prompted players to be kicked off NCAA Division I teams| Westchester Community College to cancel two consecutive men�s basketball seasons and a women's season and sparked an NJCAA investigation into WCC going back years. It forced WCC to admit to NJCAA violations. The head WCC men's coach was charged with nine felony counts| including counts for conduct I uncovered. My work was cited by Sports Ilustrated and The New York Times called it an 'expert investigatory dig.',It earned a Top 10 award in the Associated Press Sports Editors national contest in the Investigative Reporting category,LineEnd
# 2/3/16 16:06,Millions of STAR funds go to ineligible homeowners,http://www.lohud.com/story/money/personal-finance/taxes/david-mckay-wilson/2014/06/28/millions-ineligibly-received-star-dollars-fall-abyss/11666047/,6/29/14,David McKay Wilson,Law change| policy change| Government investigation| Public official refers to our journalism| How much our audience�s awareness or understanding has increased,The state Legislature passed a law in 2015 in which the state was required to set up a system to claw back the millions of dollars.,No Data,LineEnd
# 2/11/16 8:49,Millennials fuel Metro-North ridership surge,http://www.usatoday.com/story/news/nation-now/2016/02/10/new-york-commuter-rail/80173050/#,2/10/16,Thomas C. Zambito,Social share by key figure or organization,Retweeted by USA Today (Linda Dono) and distributed to USA Today networks. Also posted on USA Today Nation.,'USA Today created a separate URL. This is ours: http://www.lohud.com/story/news/transit/2016/02/10/millennials-metro-north/79939930/
# Story was also retweeted by a number of transportation groups| including the Tri-State Transportation Campaign. And it appeared on the website of several news sites across the country| TV| news sites etc.',LineEnd
# 3/2/16 14:34,Multimedia project incorporated in middle school curriculim,http://www.lohud.com/story/life/2015/09/10/holocaust-survivors-families/30930951/,9/1/15,Seth Harrison,multimedia project used for educational purposes,'Hillary Hazen-Glass| a Nyack educator working with the Rockland Holocaust Museum| has incorporated the L�dor Vador project into a curriculum on pluralism for upwards of 300 eighth graders at Nyack Middle School. The first group of students visited the museum this week and viewed the exhibit and documentary| and completed assignments based on what they saw. The exhibit is on display at the Rockland Holocaust Museum through March.
# ',No Data,LineEnd
# 3/6/16 21:19,Esplanade residents speak out on being force out,http://www.lohud.com/story/news/local/westchester/white-plains/2015/12/28/esplanade-residents-speak-out-being-forced-out/77372702/,12/29/15,Richard Liebson,Government investigation,We did a number of stories on plans by the Esplanade Senior Living facility in White Plains to evict 150 senior citizens and repurpose the building into luxury rental apartments. The first story appeared on Dec. 8 and outlined the plan. That was followed on Dec. 29 by a story focusing on residents reaction to the plan. A Jan. 8| 2016 story reported that the state Attorney General's Office was investigating the Esplanade's actions. A Jan. 22 story reported that state elected officials representing White Plains were drafting legislation to prevent something like this from happening in the future. On March 3| the legislation was introduced in the senate and state assembly.,This was the second story we did on plans by the Esplanade senior living facility to evict all of the seniors and repurpose the building into luxury rental apartments. On Jan. 8| the state Attorney General's Office confirmed that as a result of our story| it was investigating the Esplanade's actions. On March 3| a bill to prevent future senior residences from doing the same without prior court approval was introduced in the state senate and assembly.,LineEnd
# 3/8/16 16:18,Exclusive: Metro-North engineer in fatal Bronx derailment gets pension,http://www.lohud.com/story/news/investigations/2016/03/04/metro-north-engineer-bronx-derailment/81231178/,3/7/16,Thomas C. Zambito,Reporter followed by key figure or organization on social media| Citation (someone mentioned your journalism in an important way),'Story was picked up by the AP with credit to the Journal News as well as Reuters (w/o credit) . Version ran in USA Today and was picked up by newspapers| websites| TV stations. USA Today reader in California sent in a very promising news tip that could advance the story.
# https://news.google.com/news/story?ncl=dSdWd1Gkct6MKPM4NorWJavaZo0NM&q=william+rockefeller&lr=English&hl=en&sa=X&ved=0ahUKEwjbmrvdgbLLAhXJ2B4KHWPOD9MQqgIIJzAA',Story was picked up by the AP with credit to the Journal News as well as Reuters (w/o credit) . Version ran in USA Today and was picked up by newspapers| websites| TV stations. USA Today reader in California sent in a very promising news tip that could advance the story.,LineEnd
# 4/4/16 15:14,Paralyzed Metro-North worker losing salary as legal case continues,http://www.lohud.com/story/news/investigations/2016/03/13/paralyzed-metro-north-worker-losing-salary-legal-case-continues/81522330/,3/14/16,Thomas C. Zambito,Reporter followed by key figure or organization on social media,FOX 5 in NY producded the same story on its 10 pm newscast the night the story aired.,This is the link to the Fox News report. http://www.fox5ny.com/news/107665301-story,LineEnd
# 4/6/16 14:29,Questions surround Libby Pataki| 2 tourism agencies,http://www.lohud.com/story/money/personal-finance/taxes/david-mckay-wilson/2016/02/03/libby-pataki-cashes-putnam-tourism/79413068/,2/25/16,David McKay Wilson,Government investigation| Institutional action (firing reorganization etc.)| Public official refers to our journalism| Staff interview on other media| How much our audience�s awareness or understanding has increased| Increased civic engagement (participation in the democratic process),State Attorney Gen. Eric Schneiderman announced investigation the day after story was published online. Six weeks later| Pataki resigned. The story has been in front page stories in several local weeklies: Putnam Courier| Philipstown News & Recorder| PUtnam Examiner| Putnam Times. The website was also updated to remove the embarrassment that was there for public view.,No Data,LineEnd
# 4/6/16 15:53,Ardsley Police Investigate Cancer Fundraiser,http://www.lohud.com/story/news/2016/03/25/ardsley-police-investigate-cancer-mom-fundraiser/82121546/,3/26/16,Jonathan Bandler| Adrienne Sanders,Picked up by many media outlets| college websites etc.,Many media outlets including at least one popular college website picked up our story. Most rewrites included incorrect information.,'There is also a timeline and a video to this story.
#
# A few of the sites: http://newyork.cbslocal.com/2016/03/27/cancer-fundraising-investigation/
# http://www.insideedition.com/headlines/15528-police-investigating-fundraising-efforts-of-woman-claiming-to-have-terminal-cancer
# http://rivertowns.dailyvoice.com/neighbors/ardsley-teen-raising-money-for-his-single-mom-with-cancer/587861/
# http://www.nydailynews.com/life-style/health/new-york-woman-terminal-cancer-investigation-article-1.2581851
# http://www.syracuse.com/us-news/index.ssf/2016/03/mom_allegedly_fakes_cancer_for_money_then_moves.html
# http://www.dailymail.co.uk/news/article-3514157/Single-mom-two-fakes-having-just-18-months-live-cancer-scam-community-60k-skipping-town.html
# http://www.bet.com/news/national/2016/03/31/shame-on-you--single-mom-allegedly-fakes-cancer.html',LineEnd
# 5/6/16 12:31,Hasidic teens risk shunning for schooling,http://www.lohud.com/story/news/investigations/2016/04/20/east-ramapo-education/82519112/,4/24/16,Adrienne Sanders,Advocacy organization uses our journalism| Change in societal behavior| How much our audience�s awareness or understanding has increased| Made inroads in a community not often represented in our journalism,The subject of this story's main bar| Mendel Taub| told me that young people in his New Square Hasidic community approached him after our story ran about pursuing their own secular education beyond the yeshivas. The story was secretly shared on WhatsApp by community members who are prohibited from using the internet. The story was disseminated by many of the colleges mentioned in the piece. For example| the President of RCC sent it to members of his Board of Trustees and it appeared in the college's monthly publication. Yaffed's Naftuli Moster and author Shulem Deen| both Hasidic education advocates| widely shared all pieces of this package.,This is part of our continuing coverage on the subject. Our past coverage was recognized among Hasidim and former Hasidim| which led to many people wanting to be included in this story. I had to turn down several interested subjects.,LineEnd
# 5/6/16 12:51,Jaffee bill seeks stronger oversight of private schools,http://www.lohud.com/story/news/education/2016/05/02/jaffee-bill-east-ramapo/83841028/,5/4/16,Adrienne Sanders,Law change| policy change| Advocacy organization uses our journalism| Social share by key figure or organization| How much our audience�s awareness or understanding has increased,Since we began investigating the lack of secular education in Hasidic yeshivas| a lawsuit on the issue was filed and two bills seeking stricter oversight of private schools were introduced to the state Assembly. This one is the most recent| drafted by Assemblywoman Ellen Jaffee| D-Suffern.,East Ramapo's troubled public schools have received media attention for years. This year| due in large part to our coverage| people are now talking (tweeting| posting| filing lawsuits) about educational deficiencies in the district's private schools. This bill is the latest example of that.,LineEnd
# 5/16/16 14:06,Taxpayers pony up for counties' private lawyers,http://www.lohud.com/story/news/investigations/2016/05/11/rockland-westchester-legal-bills/32592507/,5/12/16,Jorge Fitz-Gibbon,How much our audience�s awareness or understanding has increased,My story on outsourced legal work by county governments prompted Rockland County officials to disclose nearly $2.7 million in additional payments to private law firms than they had initially revealed in response to a Freedom of Information Law request. This occurred after I published a watchdog story on the tax dollars spent on attorneys on May 11| 2016. After reading my story| Rockland County officials began to scrutinize the numbers I published| convinced that the figure for 2015 had decreased from prior years| not risen| as my story showed. What they found is that they had failed to reveal $2.68 million in additional spending between 2009 and 2014. Based on the new data provided| I re-worked the story and re-published on May 12| 2016 to inform readers that significantly more of their tax dollars had been used to hire private lawyers.,In what may be a future impact that I will monitor| Rockland County Attorney Thomas Humbach said that the startling numbers in my story could pressure county lawmakers to provide him funding to hire two new in-house attorneys that would reduce reliance on private lawyers. Humbach said he has been denied the request in past budget discussions.,LineEnd
# 5/18/16 9:47,Overdose deaths across the nation kick off conference on opioid abuse,http://www.lohud.com/story/news/local/blogs/thepound/2016/04/13/overdose-deaths-kick-off-conference-opioid-abuse/82994898/,4/13/16,David Robinson,Law change| policy change| Government investigation| Advocacy organization uses our journalism| Public official refers to our journalism| Staff interview on other media| Social share by key figure or organization| Reporter followed by key figure or organization on social media| Citation (someone mentioned your journalism in an important way)| Award| Change in societal behavior| How much our audience�s awareness or understanding has increased| Reader/viewer contact| Increased civic engagement (participation in the democratic process),My ongoing coverage of the opioid epidemic has gained attention at local| state and federal levels. Examples include me earning a National Press Foundation fellowship that focused on curbing the crisis. My stories in The Journal News/lohud.com reached audiences through mentions by top federal officials| along with numerous media outlets. My series in 2015 - Painkillers to Heroin: A Generation Lost -- has also been named a finalist for an Associated Press award for investigative journalism in New York. Policy and law changes include widened public access to opioid antidotes| interagency sharing of prescribing data among law enforcement and far-reaching arrests linked to drug trafficking pipelines featured in my coverage. A state task force seeking to reduce painkiller and heroin deaths has also been launched in the wake of my coverage. The task force panel includes a mother and local legislators featured in my stories and community forum. My coverage has also been mentioned and recognized by local addiction treatment service providers amid a push to improve access to services.,No Data,LineEnd
# 5/23/16 14:38,Shutdown battle: A tale of 2 nuclear power plants,http://www.lohud.com/story/news/investigations/2016/05/18/indian-point-fitzpatrick/83981086/,5/18/16,Thomas C. Zambito,Advocacy organization uses our journalism| Social share by key figure or organization| Reporter followed by key figure or organization on social media| Reader/viewer contact,'This story was run on the Sunday front page of our sister paper| The Rochester Democrat and Chronicle and was shared through its social media outlets. Additionally it was retweeted by nuclear energy organizations as well as groups such as Recliam New York| Cuomo Watch and Indian Point Entergy. I picked up 10 followers from this story and its leadup.
# ',No Data,LineEnd
# 5/23/16 14:46,Indian Point: Unlikely alliance backs plant's future,http://www.lohud.com/story/news/investigations/2016/05/17/indian-point-alliance/84456470/,3/17/16,Thomas C. Zambito,Social share by key figure or organization| Reporter followed by key figure or organization on social media| How much our audience�s awareness or understanding has increased| Reader/viewer contact,'Story was retweeted by Mike Shellenberger| a prominent climate change scientist as well as several of his Twitter followers. I picked up five followers from this group as a result of the story. And I was mentioned in a number of climate change-related retweets.
# This story was a lead-up to a story on a state hearing on the future of nuclear power plants. It and other generated roughly 50 link clicks based on Twitter activity.
# ',No Data,LineEnd
# 6/3/16 11:27,Metro-North engineers| conductors suspended for cheating,http://www.lohud.com/story/news/investigations/2016/06/01/metro-north-cheating-scandal/85242264/,6/1/16,Thomas C. Zambito,Social share by key figure or organization| Citation (someone mentioned your journalism in an important way),This story was mentioned on the Rush Limbaugh show| retweeted by key transportation figures in the Metro New York area and led the 6/2 evening news report on Fox5Ny. http://www.fox5ny.com/news/151984057-story,Separately| this story generated behind-the-scenes meetings between top union officials and Metro-North| as well as the state Inspector General's office and MTA| which may be the subject of future stories.,LineEnd
# 6/17/16 11:04,German restaurants: Sour Kraut in Nyack is back,http://www.lohud.com/story/life/food/restaurants/2016/06/16/german-restaurant-sour-kraut-nyack/85991118/,6/16/16,Liz Johnson,Institutional action (firing reorganization etc.)| Public official refers to our journalism| Change in behavior from a business owner,In January| 2016| Liz Johnson reported on the closure of Sour Kraut in Nyack| one of the last remaining German restaurants| listing the last three in the region (none in Rockland). The owner was going to turn it into a speakeasy. In June| the owner called to say she would be reopening: as a German restaurant. She'd seen the piece saying there were very few restaurants left| and gotten enough calls from fans of German food| that she decided to fill the void she'd left by closing.,Here is the original story: http://www.lohud.com/story/life/food/restaurants/2016/01/08/sour-kraut-closes/78524112/,LineEnd
# 6/29/16 14:52,Investigation: Top hospital execs| docs get millions,http://www.lohud.com/story/news/investigations/2016/06/02/new-york-hospital-payouts/85027532/,6/5/16,David Robinson,Institutional action (firing reorganization etc.)| Advocacy organization uses our journalism| Staff interview on other media| Social share by key figure or organization| Reporter followed by key figure or organization on social media| Citation (someone mentioned your journalism in an important way)| How much our audience�s awareness or understanding has increased| Reader/viewer contact| Increased civic engagement (participation in the democratic process)| Another media organization publishes our work,The project was published in USA TODAY Network properties across New York| including The Journal News/lohud; Rochester Democrat & Chronicle; and the Poughkeepsie Journal. It attracted 17|000 unique visitors to lohud| alone| and the reporter| David Robinson| was interviewed on WVOX's 'Good Morning Westchester' radio program. Lohud audience engagement included 917 Facebook connect actions| 63 LinkedIn actions. Online discussions included more than 50 reader comments via lohud and Facebook. Advocacy groups| including health care unions New York State Nurses Association and SEIU| shared the project through their social media accounts| including links to the project's searchable database of nonprofit hospital compensation on lohud's NY Databases. Reader contacts included emails and calls to the reporter. One email came from a former hospital board member. He said he left the board previously because of concerns about the rising executive compensation exposed in the lohud project. Another call came from a nurse at a local hospital. She said the nursing staff learned their pay was capped just before the lohud project published. She is organizing opposition to nurse pay cap based on the findings of the lohud report.,No Data,LineEnd
# 7/22/16 12:46,Libby Pataki to dissolve tourism nonprofit,http://www.lohud.com/story/money/personal-finance/taxes/david-mckay-wilson/2016/07/21/libby-pataki-putnam-tourism/87345144/,7/20/16,David McKay Wilson,Law change| policy change| Government investigation| Institutional action (firing reorganization etc.)| Increased civic engagement (participation in the democratic process),the story led to Libby Pataki's resignation as tourism director| the dissolution of one nonprofit| and the reconstituting of another| with a proper board of directors and appropriate oversight,My investigation of Libby Pataki's tenure as tourism director led to her resignation and an investigation by Attorney Gen. Eric Scheiderman. He ordered that the nonprofit Visitors Bureau be reconstituted| with a functioning board| and bylaws. He also won an agreement from Pataki to dissolve the Putnam Tourism Corp.| which Pataki had referred to as her 'foundation.' She is no longer associated with either nonprofit.,LineEnd
# 8/16/16 13:08,State Investigates Ramapo Valley Ambulance Corps,http://www.lohud.com/story/news/investigations/2016/07/14/ramapo-ambulance-investigation/86600706/,7/17/16,Adrienne Sanders,Reporter followed by key figure or organization on social media| Citation (someone mentioned your journalism in an important way)| How much our audience�s awareness or understanding has increased| Internal investigation launched,Several news outlets including CBS and News 12 followed our story about management misdeeds at Ramapo Valley Ambulance Corps. The corps' attorney launched an investigation into the malfeasance alleged in our story. (See related impact tracker submission.),No Data,LineEnd
# 8/16/16 13:21,RVAC launches internal investigation in response to lohud report,http://www.lohud.com/story/news/investigations/2016/08/15/ravc-internal-investigation-lohud-report/88764196/,8/15/16,Adrienne Sanders,Citation (someone mentioned your journalism in an important way)| internal investigation,RVAC's lawyer Dennis Lynch said his firm was looking into RVAC's 'many complaints that ... came to us through The Journal News.' He promised disciplinary action if wrongdoing was discovered.,No Data,LineEnd
# 9/2/16 18:17,PepsiCo to reopen sculpture garden in March,http://preview.lohud.com/story/money/business/2016/09/02/pepsico-sculpture-garden/89350916/,9/2/16,Akiko Matsuda,Law change| policy change,PepsiCo pledged to reopen the Donald M. Kendall Sculpture Gardens in March 2017 after the company saw our article| reporting that the popular facility has remained closed to the public even though the world headquarters reopened for operation after a major renovation project.,PepsiCo wanted us to say the company will open the park to the public in the future without specifying the date. We demanded that we have to know when and how. At the end| PepsiCo came back to tell us it'll be open in March 2017| though the company still has to work out the logistics.,LineEnd"
#
# headers = ["Timestamp","Headline","URL","Publication date","Reporter","Impact","Impact Description","Info","LineEnd"]
#
# articles = articles.split("LineEnd")
#
# articles_hashes = articles.map do |article|
#   sections = article.split(",")
#    sections.each_with_object({}).with_index do |(section, hash), i|
#     hash[headers[i]] = section.gsub('|',',')
#   end
# end
#
# articles_hashes.each do |article_hash|
#   reporter = Reporter.find_or_create_by({name: article_hash["Reporter"]})
#   reporter.save
#   article = Article.find_or_create_by({url: article_hash["URL"]})
#   article.headline = article_hash["Headline"]
#   article.date = article_hash["Publication date"]
#   article.info = article_hash["Info"]
#   article.save
#   reporter_article = ReporterArticle.create({article_id: article.id, reporter_id: reporter.id})
#   reporter_article.save
# end
#
# articles_hashes.each do |article_hash|
#   impact_desc = article_hash["Impact Description"]
#   impacts = article_hash["Impact"].split(",")
#   impacts.each do |current_impact|
#     impact = Impact.find_or_create_by({description: impact_desc})
#     impact_type = ImpactType.find_or_create_by({name: current_impact})
#     impact_type.save
#     article = Article.find_or_create_by({url: article_hash["URL"]})
#     article_impact = ArticleImpact.find_or_create_by({impact_id: impact.id, article_id: article.id, description: article_hash["ImpactDescription"]})
#     article_impact.save
#     impact_record = ImpactRecord.find_or_create_by({impact_id: impact.id, impact_type_id: impact_type.id, article_id: article.id})
#     impact_record.save
#   end
# end
#
#
# # puts articles.length
